### ISSUE TITLE
Edit of contact form and creation of landing page for webinar

### ISSUE THREAD

**Issue by enonied4g** [unicef/drone-4sdgtoolkit#13]
Hello @jwflory and @Idadelveloper 

I discussed with Justin the development of a landing page of the Drones 4 SDG Toolkit webinar on the 28th of October. 

We decided to develop a new page that details the webinar date and information and that page will link to the contact us form for people to RSVP for the event. 

The RSVP form should have the following fields. 

Name: (required)
Organization: (required) 
Email: (required)
How do you work with drones?:

I'll work on the content for the webinar page.

**Comment by jwflory** [comment]
The RSVP form is implemented in the following pull requests. This issue can be closed once the webinar page copy is prepared and pushed to the site.

* unicef/inventory-hugo-theme#26
* unicef/drone-4sdgtoolkit#15
